# Numpy Toots for Noobs

## Data Beta - Pragyaditya

## Chapter 1: Numpy Basics & Matrix Operations

Loose inspiration driven from - [freeCodeCamp](https://www.freecodecamp.org/news/the-ultimate-guide-to-the-numpy-scientific-computing-library-for-python/) and [towardsDataScience](https://towardsdatascience.com/top-10-matrix-operations-in-numpy-with-examples-d761448cb7a8)

In [1]:
import numpy as np

In [2]:
print (np.__version__)

1.21.5


In [3]:
list_sample = [1,2,3]

In [4]:
np.array(list_sample)

array([1, 2, 3])

## There are two types of arrays - Vectors : One dimensional array and Matrices : Two dimensional array

In [5]:
my_vector = np.array([1,2,3])

In [6]:
my_matrix = np.array([[1,2,3],[2,3,4],[4,3,2]])

In [7]:
my_vector

array([1, 2, 3])

In [8]:
my_matrix

array([[1, 2, 3],
       [2, 3, 4],
       [4, 3, 2]])

## Matrix Operations using Numpy - Important for Data Scientists

In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [10]:
display_a = print("a= ", a)
display_b = print("b= ", b)

a=  [1 2 3]
b=  [4 5 6]


In [11]:
dot_product = np.dot(a,b)
inner_product = np.inner(a,b)

In [12]:
dot_product

32

In [13]:
inner_product

32

In [14]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
d = np.array([[3,1,1],[5,6,6],[9,6,6]])

In [15]:
print(np.dot(c,d))

[[ 40  31  31]
 [ 91  70  70]
 [142 109 109]]


In [16]:
print(np.inner(c,d))

[[  8  35  39]
 [ 23  86 102]
 [ 38 137 165]]


In [17]:
print(c*d)

[[ 3  2  3]
 [20 30 36]
 [63 48 54]]


In [18]:
d = np.transpose(a)

In [19]:
d

array([1, 2, 3])

In [20]:
e = c.T # shortcut of transpose value

In [21]:
e

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [22]:
#Trace = sum of diagonal elements

In [23]:
f = c.trace()

In [24]:
f

15

In [25]:
#verify trace
g = sum(c.diagonal())

In [26]:
g

15

In [27]:
#rank of a matrix
r = np.linalg.matrix_rank(c)

In [28]:
r

2

In [29]:
#determinant
det = np.linalg.det(c)

In [30]:
det1 = np.round(det)


In [31]:
det1

0.0

In [32]:
# if Determinant is zero, the matrix cannot be inversed, it is also known as a singular matrix

In [33]:
det2 = np.round(np.linalg.det(c))

In [34]:
det2

0.0

In [35]:
x = np.array([[2,2,1],[1,3,1],[1,2,2]])
x_det = np.round(np.linalg.det(x))
x_det

5.0

In [36]:
# Matrix x is invertible

In [37]:
#true inverse

In [38]:
x_inv = np.linalg.inv(x)
x_inv

array([[ 0.8, -0.4, -0.2],
       [-0.2,  0.6, -0.2],
       [-0.2, -0.4,  0.8]])

In [39]:
#Pseudo inverse for 

In [40]:
z = np.array([[2,8],[1,4]])
z_det = np.round(np.linalg.det(z))
z_det

0.0

In [41]:
z_pinv = np.linalg.pinv(z)

In [42]:
z_pinv

array([[0.02352941, 0.01176471],
       [0.09411765, 0.04705882]])

In [43]:
#The true inverse and pseudo inverse will be same if the matrix is invertible

In [44]:
x_pinv = np.linalg.pinv(x)

In [45]:
x_pinv

array([[ 0.8, -0.4, -0.2],
       [-0.2,  0.6, -0.2],
       [-0.2, -0.4,  0.8]])

In [46]:
#matrix flatten - convert a two dimensional to one dimersional matrix

In [47]:
x_pinv_flat = x_pinv.flatten()

In [48]:
x_pinv_flat

array([ 0.8, -0.4, -0.2, -0.2,  0.6, -0.2, -0.2, -0.4,  0.8])

In [49]:
#Eigen values and eigen vectors

In [50]:
z

array([[2, 8],
       [1, 4]])

In [51]:
evalue, evector = np.linalg.eig(z)

In [52]:
evalue

array([0., 6.])

In [53]:
evector

array([[-0.9701425 , -0.89442719],
       [ 0.24253563, -0.4472136 ]])