# Numpy Toots for Noobs

## Chapter 1: Numpy Basics & Matrix Operations

Loose inspiration driven from - [freeCodeCamp](https://www.freecodecamp.org/news/the-ultimate-guide-to-the-numpy-scientific-computing-library-for-python/) and [towardsDataScience](https://towardsdatascience.com/top-10-matrix-operations-in-numpy-with-examples-d761448cb7a8)

In [21]:
import numpy as np

In [22]:
print (np.__version__)

1.21.5


In [23]:
list_sample = [1,2,3]

In [24]:
np.array(list_sample)

array([1, 2, 3])

## There are two types of arrays - Vectors : One dimensional array and Matrices : Two dimensional array

In [25]:
my_vector = np.array([1,2,3])

In [26]:
my_matrix = np.array([[1,2,3],[2,3,4],[4,3,2]])

In [27]:
my_vector

array([1, 2, 3])

In [28]:
my_matrix

array([[1, 2, 3],
       [2, 3, 4],
       [4, 3, 2]])

## Matrix Operations using Numpy - Important for Data Scientists

In [29]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [30]:
display_a = print("a= ", a)
display_b = print("b= ", b)

a=  [1 2 3]
b=  [4 5 6]


In [31]:
dot_product = np.dot(a,b)
inner_product = np.inner(a,b)

In [32]:
dot_product

32

In [33]:
inner_product

32

In [34]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
d = np.array([[3,1,1],[5,6,6],[9,6,6]])

In [35]:
print(np.dot(c,d))

[[ 40  31  31]
 [ 91  70  70]
 [142 109 109]]


In [36]:
print(np.inner(c,d))

[[  8  35  39]
 [ 23  86 102]
 [ 38 137 165]]


In [37]:
print(c*d)

[[ 3  2  3]
 [20 30 36]
 [63 48 54]]


In [38]:
d = np.transpose(a)

In [39]:
d

array([1, 2, 3])

In [44]:
e = c.T # shortcut of transpose value

In [45]:
e

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [46]:
#Trace = sum of diagonal elements

In [49]:
f = c.trace()

In [50]:
f

15

In [52]:
#verify trace
g = sum(c.diagonal())

In [53]:
g

15

In [54]:
#rank of a matrix
r = np.linalg.matrix_rank(c)

In [55]:
r

2

In [56]:
#determinant
det = np.linalg.det(c)

In [58]:
det1 = np.round(det)


In [59]:
det1

0.0

In [61]:
# if Determinant is zero, the matrix cannot be inversed, it is also known as a singular matrix

In [63]:
det2 = np.round(np.linalg.det(c))

In [64]:
det2

0.0

In [67]:
x = np.array([[2,2,1],[1,3,1],[1,2,2]])
x_det = np.round(np.linalg.det(x))
x_det

5.0

In [68]:
# Matrix x is invertible

In [69]:
#true inverse

In [71]:
x_inv = np.linalg.inv(x)
x_inv

array([[ 0.8, -0.4, -0.2],
       [-0.2,  0.6, -0.2],
       [-0.2, -0.4,  0.8]])

In [ ]:
#Pseudo inverse for 