## Chapter - 2 : SVD, PCA, Vizualizations - [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html)

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2],[3,2]])

In [4]:
a.shape

(2, 2)

In [9]:
b = np.random.randn(9, 6) + 1j*np.random.randn(9, 6)

In [10]:
b

array([[ 0.5061544 -0.05667447j,  0.66363695+0.88903838j,
        -0.26623386+0.47173557j,  1.58276005-1.71598626j,
        -0.59896969-1.72461375j, -1.40128706+2.04203106j],
       [ 0.61008489+0.50089184j, -0.34172227+0.97578296j,
         0.87453791-0.55825453j,  0.71760162-1.6910868j ,
        -0.59656671+1.02810915j, -0.43089702-0.57696836j],
       [ 0.03513657+0.3355498j , -1.11929602-0.29949187j,
         2.15924375-0.0121836j ,  1.76529966-1.14986555j,
         0.56871285-0.97685181j, -0.76195601+0.00780537j],
       [ 0.46098737+0.99352226j,  1.64278639+0.65199196j,
        -1.16829298-1.45619534j, -0.61720098+1.09981003j,
        -0.62568849-1.65502251j, -0.09873937-1.82033408j],
       [ 0.35480242-0.38378916j, -0.21299142+0.21949393j,
        -0.89738919-2.0373432j ,  1.16427126-0.21384133j,
         0.20236602-0.10371996j, -0.40902623+0.29452059j],
       [ 0.4607549 -0.28286143j,  0.21289807-0.24417348j,
         1.24829775-2.53295917j, -0.01918465+0.31082397j,
         

In [11]:
c = np.random.randn(2, 7, 8, 3) + 1j*np.random.randn(2, 7, 8, 3)

In [12]:
c

array([[[[ 1.77915977e-01+2.93171713e-01j,
           8.59857609e-02-3.17765704e-01j,
           4.25486911e-01+1.01668783e+00j],
         [ 3.68322781e-01-4.55665413e-01j,
           3.40649143e-01-1.19891820e+00j,
          -7.82601417e-01+1.75332167e+00j],
         [ 1.28501031e+00-4.21038969e-01j,
          -3.11012644e+00+6.69287561e-01j,
           1.57670530e+00+3.20770655e-01j],
         [-4.43204482e-01-1.10135824e+00j,
           1.49430988e+00-2.44257190e-01j,
           3.74745075e-02+4.62842209e-01j],
         [ 5.89642418e-01+1.05407380e+00j,
           8.33893308e-01+4.36255084e-01j,
          -1.00561624e+00+8.25009644e-01j],
         [-1.05535934e+00-5.05080208e-01j,
           2.32748707e-01+8.92292421e-01j,
          -9.63829867e-01-2.21954204e-01j],
         [ 2.01814335e+00+2.52334957e+00j,
           7.34339658e-01+8.08007803e-01j,
          -6.81446834e-01+8.63012113e-01j],
         [-2.06295044e+00+2.53121933e-01j,
           2.16220079e-02-3.53030483e-01j,
    

In [13]:
u, s, vh = np.linalg.svd(a, full_matrices=True)

In [14]:
u

array([[-0.50192682, -0.86491009],
       [-0.86491009,  0.50192682]])

In [15]:
s

array([4.13064859, 0.96837093])

In [16]:
vh

array([[-0.74967818, -0.66180256],
       [ 0.66180256, -0.74967818]])

In [17]:
u.shape, s.shape, vh.shape

((2, 2), (2,), (2, 2))

In [18]:
ub, sb, vhb = np.linalg.svd(b, full_matrices=True)

In [19]:
ub.shape, sb.shape, vhb.shape

((9, 9), (6,), (6, 6))

In [20]:
ub

array([[ 0.17729908+0.24599565j,  0.52216147-0.13080987j,
        -0.00542396-0.26965857j,  0.04736414-0.41712688j,
         0.07130339+0.37747643j,  0.21888695-0.03062106j,
         0.15291467+0.12851658j,  0.13350211+0.33471753j,
        -0.04581961+0.03201162j],
       [-0.20365699+0.01409511j,  0.18039298-0.12408526j,
        -0.22967041-0.31345427j, -0.02639271+0.15849295j,
        -0.07333544-0.29073479j,  0.53787388+0.26347273j,
        -0.03149563-0.19954925j, -0.10769047-0.20235867j,
        -0.2020034 +0.38829524j],
       [-0.33991845-0.01240874j,  0.3981763 -0.07383757j,
         0.27157531-0.23563359j, -0.04379734-0.08108459j,
         0.08743173-0.01798624j, -0.18422199-0.40489176j,
        -0.02403272-0.31312447j, -0.22968071-0.38751506j,
         0.21564869-0.16924229j],
       [ 0.03432784+0.25380869j, -0.47941922+0.3082331j ,
        -0.09652262-0.31643706j,  0.13760753-0.15197139j,
         0.26452196+0.35340391j,  0.15091249-0.11933641j,
        -0.21782005-0.317171

In [21]:
sb

array([6.03843149, 5.30532819, 4.75029862, 3.81177811, 2.42429934,
       1.57943586])

In [22]:
vhb

array([[-0.12973213+0.j        ,  0.16153311-0.10911588j,
        -0.774043  +0.30465492j, -0.05992744-0.08227904j,
        -0.25790808-0.09602221j,  0.21456921+0.34795868j],
       [ 0.16238461+0.j        , -0.22603879-0.09000329j,
         0.11169143+0.28869681j,  0.54599024-0.31400352j,
         0.01359723+0.08946673j, -0.44660137+0.4628939j ],
       [-0.4871045 +0.j        , -0.25071558-0.08137274j,
         0.03463741+0.00119502j,  0.45019002+0.18507031j,
         0.37594185-0.42088576j,  0.3671938 +0.04263494j],
       [ 0.58748994+0.j        , -0.19616382+0.34483882j,
        -0.31063619+0.21832504j, -0.04311419-0.00307728j,
         0.53206516-0.19123006j,  0.06036244-0.16771004j],
       [ 0.60639509+0.j        ,  0.17276152-0.36082541j,
         0.12866509-0.22149273j,  0.30289917+0.1923829j ,
        -0.24074956-0.14626904j,  0.42656068+0.12869212j],
       [-0.08167365+0.j        ,  0.66093408+0.28117146j,
        -0.03416735+0.00888838j,  0.43456807-0.19114507j,
         